apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: derryukere/star-wars:latest
            envFrom:
            - secretRef:
                name: demo-secret
            imagePullPolicy: IfNotPresent
            command:
            - npm
            - start
          restartPolicy: OnFailure